#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#endif

#define END 0
#define AUTO 1
#define BREAK 2
#define CASE 3
#define CHAR 4
#define CONST 5
#define CONTINUE 6
#define DEFAULT 7
#define DO 8
#define DOUBLE 9
#define ELSE 10
#define ENUM 11
#define EXTERN 12
#define FLOAT 13
#define FOR 14
#define GOTO 15
#define IF 16
#define INLINE 17  
#define INT 18
#define LONG 19
#define REGISTER 20
#define RESTRICT 21
#define RETURN 22
#define SHORT 23
#define SIGNED 24
#define SIZEOF 25
#define STATIC 26
#define STRUCT 27
#define SWITCH 28
#define TYPEDEF 29 
#define UNION 30
#define UNSIGNED 31
#define VOID 32
#define VOLATILE 33  
#define WHILE 34
#define _BOOL 35
#define _COMPLEX 36
#define _IMAGINARY 37
#define CONSTANT 38
#define STRING_LITERAL 39
#define ASSIGN 40
#define ADD 41
#define SUB 42
#define MUL 43
#define DIV 44
#define MOD 45
#define AND 46
#define XOR 47
#define OR 48
#define L_OP 49
#define G_OP 50
#define ADD_ASSIGN 51
#define SUB_ASSIGN 52
#define MUL_ASSIGN 53
#define DIV_ASSIGN 54
#define MOD_ASSIGN 55
#define AND_ASSIGN 56
#define XOR_ASSIGN 57
#define OR_ASSIGN 58
#define AND_OP 59
#define OR_OP 60
#define LE_OP 61
#define GE_OP 62
#define EQ_OP 63
#define NE_OP 64
#define COND_OP 65
#define END_OF_INSTRUCTION 66
#define IDENTIFIER 67